# Generated by Django 5.0.4 on 2025-02-21 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_eventregistration_delete_uniquebrand'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniqueBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=25, unique=True)),
            ],
        ),
    ]
